import 'package:flutter/material.dart';
import 'package:flutterapp/app_shopapp/generatedwidget/generated/GeneratedBodyWidget.dart';
import 'package:flutterapp/app_shopapp/generatedwidget/generated/GeneratedActionWidget.dart';
import 'package:flutterapp/app_shopapp/generatedwidget/generated/GeneratedNavbottomWidget.dart';
import 'package:flutterapp/app_shopapp/generatedwidget/generated/GeneratedStatusBarWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/app_shopapp/generatedwidget/generated/GeneratedNavtopWidget.dart';

/* Frame  
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(45.48882293701172),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 3375.2709045410156,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 941.6187133789062,
                            height: 2551.923095703125,
                            decoration: BoxDecoration(
                              borderRadius:
                                  BorderRadius.circular(45.48882293701172),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.circular(
                                        45.48882293701172),
                                    child: Container(
                                      color: Color.fromARGB(255, 252, 248, 248),
                                    ),
                                  ),
                                  Positioned(
                                    left: -8.52445964483195e-7,
                                    top: 282.0307312011719,
                                    right: 8.52445964483195e-7,
                                    bottom: null,
                                    width: null,
                                    height: 2176.640380859375,
                                    child: GeneratedBodyWidget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 61.409915924072266,
              top: 3200.138916015625,
              right: null,
              bottom: null,
              width: 818.7988891601562,
              height: 175.13198852539062,
              child: GeneratedActionWidget(),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: -0.0001220703125,
              width: 941.6187133789062,
              height: 193.4044189453125,
              child: TransformHelper.translate(
                  x: -0.00, y: 0.00, z: 0, child: GeneratedNavbottomWidget()),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 941.6187133789062,
              height: 122.81983184814453,
              child: GeneratedStatusBarWidget(),
            ),
            Positioned(
              left: -8.52445964483195e-7,
              top: 122.81983184814453,
              right: null,
              bottom: null,
              width: 941.6187133789062,
              height: 172.8575439453125,
              child: GeneratedNavtopWidget(),
            )
          ]),
    ));
  }
}
