import 'package:flutter/material.dart';
import 'package:flutterapp/app_shopapp/generatedwidget3/generated/GeneratedGroup3388Widget.dart';

/* Frame  
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(45.48882293701172),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 3188.76708984375,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 941.6187133789062,
                            height: 3188.766845703125,
                            decoration: BoxDecoration(
                              borderRadius:
                                  BorderRadius.circular(45.48882293701172),
                            ),
                            child: ClipRRect(
                              borderRadius:
                                  BorderRadius.circular(45.48882293701172),
                              child: Container(
                                color: Color.fromARGB(255, 252, 248, 248),
                              ),
                            ),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 941.6187133789062,
              height: 3188.76708984375,
              child: GeneratedGroup3388Widget(),
            )
          ]),
    ));
  }
}
